language: julia
install: bash install/dependencies.sh
sudo: false
os:
    - linux
    - osx
julia:
    - 0.4
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
script: make
after_success:
    - echo $TRAVIS_JULIA_VERSION
